# Generated by Django 4.2.15 on 2024-08-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=100)),
                ("revenue", models.FloatField()),
                ("conversions", models.IntegerField()),
                ("status", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
